project_id = "gpskxbeimcxwgofpxxsm"

[functions.analyze-review]
verify_jwt = true

[functions.create-new-user]
verify_jwt = true

[functions.update-user-password]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.initiate-google-oauth]
verify_jwt = true

[functions.google-oauth-callback]
verify_jwt = false

[functions.fetch-google-reviews]
verify_jwt = true

[functions.post-review-response]
verify_jwt = true
